console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log(99);
console.log("ayeha");console.log("ayeha");console.log("ayeha");console.log("ayeha");console.log("ayeha")
